name: CI (Build Qt6 Arch Linux)

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-slicer-qt6-archlinux:
    name: Build Slicer with Qt6 on Arch Linux
    runs-on: ubuntu-latest
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_MAXSIZE: 5G
      CCACHE_COMPRESS: "1"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: "Restore ccache"
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: .ccache
          key: ${{ runner.os }}-qt6-archlinux-ccache-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-qt6-archlinux-ccache-${{ github.ref_name }}-
            ${{ runner.os }}-qt6-archlinux-ccache-

      # Retrieve changes in SuperBuild-related files relative to the 'nightly-main' branch
      - name: "Detect SuperBuild Changes"
        if: github.repository == 'Slicer/Slicer'
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        id: superbuild-changes
        with:
          files: |
            SuperBuild/External_*
          base_sha: nightly-main

      # List any SuperBuild files that were changed
      - name: "List Changed SuperBuild Files"
        if: steps.superbuild-changes.outputs.any_changed == 'true'
        run: |
          echo "Changed files:"
          for file in ${ALL_CHANGED_FILES}; do
            echo " $file"
          done
        env:
          ALL_CHANGED_FILES: ${{ steps.superbuild-changes.outputs.all_changed_files }}

      # Check prerequisites for the build
      - name: "Check Prerequisites"
        id: check-prerequisites
        run: |
          if [[ $SUPERBUILD_CHANGED == "true" ]]; then
            echo "::warning ::Skipping Qt6 Arch Linux Slicer build due to changes in SuperBuild files relative to 'nightly-main' branch."
          fi
        env:
          SUPERBUILD_CHANGED: ${{ steps.superbuild-changes.outputs.any_changed || 'false' }}

      # Build Slicer with Arch Linux Qt6 packages.
      - name: "Build Slicer with Qt6 on Arch Linux"
        id: slicer-build-qt6-archlinux
        if: ${{ steps.superbuild-changes.outputs.any_changed != 'true' }}
        uses: ./.github/actions/slicer-build-qt6-archlinux
